Shop.create!(
	name: "CHA CA（茶花）",
	image_path: "shops/chaka/main.jpeg",
	catch: "落ち着いた空間でゆったりと。ショッピングの休憩にゆっくりできるデパート内のカフェ",
	owner_name: 'オーナーの名前',
	owner_image_path: 'owner_sample.jpg',
	owner_profile: 'オーナーのプロフィール',
	description: "コンセプトは「食が健康な身体を作る」。ヘルシーな食材を取り入れた料理を提供しているカフェレストラン。静岡伊勢丹の中にあり、ショッピングの途中や街中で働く方のランチ、仕事帰りにも利用しやすい。玄米、大豆ミート、野菜といった材料をメインにした料理には、できるかぎり体にやさしい食材を使用。健康を意識した食事ができる。木のぬくもりを感じられる内装は落ち着いた雰囲気で、街中にありながらゆったりと過ごせる。",
	description_image: "/shops/chaka/desc_image.jpeg",
	address: "420-0031 静岡県静岡市葵区呉服町1-7 静岡伊勢丹4F",
	learn_image1: 'dummy.png',
	learn_image2: 'dummy.png',
	learn_image3: 'dummy.png',
	learn_point1: '学ぶポイント１',
	learn_point2: '学ぶポイント２',
	learn_point3: '学ぶポイント３',
	learn_day1: '一日目の内容です一日目の内容です一日目の内容です一日目の内容です一日目の内容です',
	learn_day2: '二日目の内容です',
	learn_day3: '三日目の内容です三日目の内容です三日目の内容です三日目の内容です三日目の内容です三日目の内容です三日目の内容です三日目の内容です',
)

Shop.create!(
	name: "すろ～カフェ モミの木",
	image_path: "shops/momi/main.jpeg",
	catch: "やさしくて、おいしいスローな暮らしを「食」から提案",
	owner_name: 'オーナーの名前',
	owner_image_path: 'owner_sample.jpg',
	owner_profile: 'オーナーのプロフィール',
	description: "18年間にわたり親しまれてきた藤枝の人気ケーキ店が2014年にリニューアル。オーガニック素材を使った体にやさしいメニューの提供を通じて、スローな暮らしを提案する。厳選した野菜や国産小麦をふんだんに使った料理は、素材の味がしっかり。また、人気の低糖質＆グルテンフリースコーンも、動物性原料不使用だということを感じさせない味わい。",
	description_image: "/shops/momi/desc_image.jpeg",
	address: "426-0071 静岡県藤枝市志太1-6-7",
	learn_image1: 'dummy.png',
	learn_image2: 'dummy.png',
	learn_image3: 'dummy.png',
	learn_point1: '学ぶポイント１',
	learn_point2: '学ぶポイント２',
	learn_point3: '学ぶポイント３',
	learn_day1: '一日目の内容です一日目の内容です一日目の内容です一日目の内容です一日目の内容です',
	learn_day2: '二日目の内容です',
	learn_day3: '三日目の内容です三日目の内容です三日目の内容です三日目の内容です三日目の内容です三日目の内容です三日目の内容です三日目の内容です',
	)
